name: Build and Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions block
permissions:
  contents: read
  issues: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create labels
        run: |
          # Create security label if it doesn't exist
          gh label create "security" --color "FF0000" --description "Security related issues" || true
          # Create high-priority label if it doesn't exist
          gh label create "high-priority" --color "FF0000" --description "High priority issues" || true

      - name: Run security audit
        run: |
          # Run npm audit and store the output
          AUDIT_OUTPUT=$(npm audit --json || true)
          echo "$AUDIT_OUTPUT" > audit-report.json
          
          # Use jq to check for high or critical vulnerabilities
          if jq -e '.metadata.vulnerabilities.high > 0 or .metadata.vulnerabilities.critical > 0' audit-report.json > /dev/null; then
            echo "Found high or critical vulnerabilities!"
            
            # Create a detailed report
            echo "## Security Audit Report" > security-report.md
            echo "### High and Critical Vulnerabilities Found" >> security-report.md
            echo "\`\`\`json" >> security-report.md
            cat audit-report.json >> security-report.md
            echo "\`\`\`" >> security-report.md
            
            # Create an issue with the findings
            gh issue create \
              --title "Security Audit: High/Critical Vulnerabilities Found" \
              --body-file security-report.md \
              --label "security" \
              --label "high-priority"
            
            exit 1
          else
            echo "No high or critical vulnerabilities found."
          fi

  build:
    needs: security-scan
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: electron-secure-defaults:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run build in container
      run: |
        docker run --rm \
          -v "$(pwd)/package:/app/package" \
          electron-secure-defaults:latest

    - name: Build DMG locally
      run: |
        npm install
        npm run build
        npm run package:mac

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-secure-defaults
        path: |
          package/*.dmg
          package/*.zip

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Create build notification
        if: needs.build.result == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const buildUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const commitUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/commit/${context.sha}`;
            
            const body = `
            ## Build Completed Successfully! 🎉

            ### Build Details:
            - **Build URL:** [View Build](${buildUrl})
            - **Commit:** [${context.sha.substring(0, 7)}](${commitUrl})
            - **Branch:** ${context.ref.replace('refs/heads/', '')}
            - **Triggered by:** ${context.actor}
            - **Build completed at:** ${new Date().toISOString()}

            You can download the packaged application from the GitHub Actions artifacts.
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Build Success: ${context.ref.replace('refs/heads/', '')} - ${new Date().toISOString()}`,
              body: body,
              labels: ['build-success']
            }); 